modLoader="javafml" #mandatory

loaderVersion="[34,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="GNU General Public License v3.0"

issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory

modId="skyblockenchantments" #mandatory

version="1.5.63 (1.16.3)" #mandatory

displayName="skyblockenchantments" #mandatory

credits="Hypixel Skyblock, everyone who tested this mod. AND YOU! I hope you enjoy." #optional

authors="HiddenMessage" #optional

description=''' HiddenMessage's Mod  '''

[[dependencies.skyblockenchantments]] #optional

    modId="forge" #mandatory

    mandatory=true #mandatory

    versionRange="[34,)" #mandatory

    ordering="NONE"

    side="BOTH"
# Here's another dependency
[[dependencies.skyblockenchantments]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
